export const ADMINISTRATION_SYMBOL: symbol = Symbol('QUEELAG_REACT_STATE_MANAGER_ADMINISTRATION')
export const IS_PROXY_KEY: string = 'isProxy'
export const PARENT_OBJECT_SYMBOL: symbol = Symbol('QUEELAG_REACT_STATE_MANAGER_PARENT_OBJECT')
