export enum ComponentLifeCycle {
  CONSTRUCTED = 'CONSTRUCTED',
  MOUNTED = 'MOUNTED',
  UNMOUNTED = 'UNMOUNTED'
}

export enum LoggerName {
  MODULE = 'ARACNA_REACT_STATE_MANAGER_MODULE'
}

export enum WatcherObservableType {
  MAP_ENTRIES = 'MAP_ENTRIES',
  MAP_GET = 'MAP_GET',
  MAP_KEYS = 'MAP_KEYS',
  MAP_VALUES = 'MAP_VALUES',
  PROXY_HANDLER_GET = 'PROXY_HANDLER_GET',
  SET_ENTRIES = 'SET_ENTRIES',
  SET_KEYS = 'SET_KEYS',
  SET_VALUES = 'SET_VALUES'
}

export enum WatcherType {
  AUTORUN = 'AUTORUN',
  REACTION = 'REACTION',
  READ = 'READ',
  WHEN = 'WHEN'
}

export enum WriteType {
  MAP_CLEAR = 'MAP_CLEAR',
  MAP_DELETE = 'MAP_DELETE',
  MAP_SET = 'MAP_SET',
  PROXY_HANDLER_DELETE_PROPERTY = 'PROXY_HANDLER_DELETE_PROPERTY',
  PROXY_HANDLER_SET = 'PROXY_HANDLER_SET',
  SET_ADD = 'SET_ADD',
  SET_CLEAR = 'SET_CLEAR',
  SET_DELETE = 'SET_DELETE'
}
